import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center'
    },
    title: {
        fontSize: 36,
        marginBottom: 16
    },
    androidButtonText: {
        color: 'blue',
        fontSize: 20
    },
    month: {
        marginTop: 10,
        textAlign: "center",
        alignItems: 'center',
    },
    cardContainer: {
        flex: 1,
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: 'space-around',
        marginTop: 50,
        backgroundColor: "whitesmoke",
    },
    cardTemp: {
        width: "100%", 
        height: "35%",
        backgroundColor: '#ff3385',
        margin: 17,
        marginLeft: 0,
        marginTop: 0,
        textAlign: "center",
        alignItems: 'center',
        justifyContent: 'space-around',
        borderColor: "red",
        borderRadius: 10,
    },
    card: {
        width: "100%", 
        height: "35%",
        backgroundColor: "#e6e6e6",
        margin: 17,
        marginLeft: 0,
        marginTop: 0,
        textAlign: "center",
        alignItems: 'center',
        justifyContent: 'space-around',
        borderColor: "red",
        borderRadius: 10,
    },
    cardx2: {
        width: "100%", 
        height: "50%",
        backgroundColor: '#262673',
        margin: 17,
        marginLeft: 0,
        marginTop: 0,
        textAlign: "center",
        alignItems: 'center',
        justifyContent: 'space-around',
        borderColor: "red",
        borderRadius: 10,
    },
    cardx2Blood: {
        width: "100%", 
        height: "50%",
        backgroundColor: "#00cccc",
        margin: 17,
        marginLeft: 0,
        marginTop: 0,
        textAlign: "center",
        alignItems: 'center',
        justifyContent: 'space-around',
        borderColor: "red",
        borderRadius: 10,
    },
    leftDeck: {
        width: "43%",
        marginLeft: 10
    },
    rightDeck: {
        width: "43%",
        marginRight: 10
    },
    cardType: {
        position: "absolute",
        top: 10,
        left: 10,
        fontSize: 20,
        fontWeight: "bold",
        color: "white",
    },
    cardReading: {
        position: "absolute",
        bottom: 10,
        right: 30,
        fontSize: 40,
        fontWeight: "bold",
        color: "white",
    },
    cardMetric: {
        position: "absolute",
        bottom: 10,
        right: 10,
        fontSize: 15,
        color: "white",
    },
    cardTypeBlood: {
        position: "absolute",
        top: 10,
        left: 10,
        fontSize: 20,
        fontWeight: "bold",
        color: "white",
    },
    cardReadingBlood: {
        position: "absolute",
        bottom: 30,
        right: 10,
        fontSize: 40,
        fontWeight: "bold",
        color: "white",
    },
    cardMetricBlood: {
        position: "absolute",
        bottom: 10,
        right: 10,
        fontSize: 15,
        color: "white",
    },
    cardTypeOxi: {
        position: "absolute",
        top: 10,
        left: 10,
        fontSize: 20,
        fontWeight: "bold",
        color: "white",
    },
    cardReadingOxiHeader: {
        position: "absolute",
        bottom: 60,
        right: 64,
        fontSize: 17,
        fontWeight: "bold",
        color: "white",
    },
    cardReadingOxi: {
        position: "absolute",
        bottom: 10,
        right: 35,
        fontSize: 40,
        fontWeight: "bold",
        color: "white",
    },
    cardMetricOxi: {
        position: "absolute",
        bottom: 20,
        right: 10,
        fontSize: 10,
        color: "white",
    },
    cardReadingOxiHeaderSpO2: {
        position: "absolute",
        bottom: 60,
        left: 15,
        fontSize: 17,
        fontWeight: "bold",
        color: "white",
    },
    cardReadingOxiSpO2: {
        position: "absolute",
        bottom: 10,
        left: 15,
        fontSize: 40,
        fontWeight: "bold",
        color: "white",
    },
    cardMetricOxiSpO2: {
        position: "absolute",
        bottom: 20,
        left: 70,
        fontSize: 13,
        color: "white",
    },
    calendar: {
        flex: 1,
        flexDirection: "row",
        flexWrap: "wrap",
        padding: 20,
    },
    days: {
        flex: 1,
        textAlign: "center",
    },
    line: {
        borderBottomColor: "red",
        borderBottomWidth: StyleSheet.hairlineWidth,
        padding: 8,
    },
    datesContainer: {
        flex: 1,
        flexDirection: "row",
        flexWrap: "wrap",
        padding: 20,
        marginBottom: 10,
    },
    dates: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: "transparent",
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 10,
        overflow: "hidden",
        textAlign: "center",
        fontWeight: "bold",
    },
    selectedDate: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: "red",
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 10,
        overflow: "hidden",
        backgroundColor: "powderblue",
        textAlign: "center",
        fontWeight: "bold",
    },
    fab: {
        position: 'absolute',
        margin: 16,
        right: 0,
        bottom: 0,
        backgroundColor: 'red',
    },
    calendarComponentContainer: {
        height: "100%"
    },
    calendarContainer: {
        width: "90%",
        backgroundColor: "#e6e6e6",
        borderRadius: 10,
    },
    calendarContainerParent: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    measurements: {
        alignItems: 'center',
        flex: 1,
        flexDirection: 'column',
        alignItems: 'stretch',
    },
    measurement: {
        textAlign: "center",
        alignItems: 'center',
        justifyContent: 'space-around',
        flex: 1,
        flexDirection: "row",
    },
    temperature: {
        backgroundColor: '#e6e6e6',
        margin: 30,
        marginBottom: 0,
        flex: 1,
        borderColor: "red",
        borderRadius: 10,
    },
    blood: {
        backgroundColor: '#e6e6e6',
        margin: 30,
        marginBottom: 0,
        flex: 1,
        borderColor: "red",
        borderRadius: 10,
    },
    oximeter: {
        backgroundColor: '#e6e6e6',
        margin: 30,
        justifyContent: 'space-around',
        flex: 1,
        borderColor: "red",
        borderRadius: 10,
    },
    fillParent: {
        height: "100%",
        width: "100%"
    },
    button: {
        backgroundColor: '#262673',
        margin: 30,
        flex: .4,
        borderColor: "red",
        borderRadius: 10,
        opacity: 0.9,
    },
    buttonText: {
        color: "white", 
        fontWeight: "bold", 
        fontSize: 20,
        textShadowColor: "black",
        textShadowRadius: 2,
    },
    measurementDirections: {
        backgroundColor: "#262673",
        position: "absolute",
        height: "100%",
        width: "70%",
        top: 0,
        right: 0,
        borderRadius: 10,
        zIndex: 1,
        opacity: 0.9,
    },
    vanish: {
        display: "none",
        width: 10,
        height: 10,
    },
    category: {
        position: "absolute",
        left: 50
    },
    spinner: {
        position: "absolute",
        zIndex: 2,
        width: 10,
        height: 10,
    },
    reading: {
        position: "absolute",
        right: 50,
        fontSize: 40,
        fontWeight: "bold",
        color: "#262673",
    },
    readingType: {
        position: "absolute",
        right: 40,
        top: 110,
    },
    readingSpO2: {
        position: "absolute",
        right: "50%",
        fontSize: 40,
        fontWeight: "bold",
    },
    readingTypeSpO2: {
        position: "absolute",
        right: "48%",
        top: 110,
        color: "#262673",
    },
    categorySpO2: {
        position: "absolute",
        right: "33%",
    },
    directionsText: {
        color: "white",
        textAlign: "center",
        justifyContent: 'center',
        margin: 60
    },
    denominator: {
        color: "#00cccc"
    }
});